Add TypeScript type definitions
micromark/micromark-extension-gfm pull request #3
Opened 2021-03-02 20:58 UTC by remcohaszing

This depends on micromark/micromark-extension-gfm-strikethrough#2

2021-03-02 21:05 UTC, ChristianMurphy requested changes
Thanks @remcohaszing!
When you have a chance could you look into the CI error?

2021-03-02 21:10 UTC, wooorm commented
@ChristianMurphy I think that’s the “This depends on micromark/micromark-extension-gfm-strikethrough#2” part

2021-03-02 21:26 UTC, remcohaszing commented
I'm a bit ahead of time with this one 😅

I just really need to use this package in a TypeScript project.

2021-03-03 12:43 UTC, wooorm approved these changes

2021-03-03 12:43 UTC, merged